//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetzGST.letzGST_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqRegistration", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CRequest")]
    [System.SerializableAttribute()]
    public partial class ReqRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisteredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserRoleAuthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNoField, value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisteredDateField, value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserRoleAuth {
            get {
                return this.UserRoleAuthField;
            }
            set {
                if ((this.UserRoleAuthField.Equals(value) != true)) {
                    this.UserRoleAuthField = value;
                    this.RaisePropertyChanged("UserRoleAuth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResCommon", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LetzGST.letzGST_Service.ResLogin))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LetzGST.letzGST_Service.ResOtp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LetzGST.letzGST_Service.ResProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LetzGST.letzGST_Service.ResRegistration))]
    public partial class ResCommon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResLogin", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    public partial class ResLogin : LetzGST.letzGST_Service.ResCommon {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserRoleAuthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserRoleAuth {
            get {
                return this.UserRoleAuthField;
            }
            set {
                if ((this.UserRoleAuthField.Equals(value) != true)) {
                    this.UserRoleAuthField = value;
                    this.RaisePropertyChanged("UserRoleAuth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResOtp", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    public partial class ResOtp : LetzGST.letzGST_Service.ResCommon {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OtpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OtpId {
            get {
                return this.OtpIdField;
            }
            set {
                if ((this.OtpIdField.Equals(value) != true)) {
                    this.OtpIdField = value;
                    this.RaisePropertyChanged("OtpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResProfile", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    public partial class ResProfile : LetzGST.letzGST_Service.ResCommon {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GstinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MembershipIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PanNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceTaxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TanNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vat_TinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CinNo {
            get {
                return this.CinNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CinNoField, value) != true)) {
                    this.CinNoField = value;
                    this.RaisePropertyChanged("CinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNoField, value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GstinNo {
            get {
                return this.GstinNoField;
            }
            set {
                if ((object.ReferenceEquals(this.GstinNoField, value) != true)) {
                    this.GstinNoField = value;
                    this.RaisePropertyChanged("GstinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogoUrl {
            get {
                return this.LogoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoUrlField, value) != true)) {
                    this.LogoUrlField = value;
                    this.RaisePropertyChanged("LogoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipId {
            get {
                return this.MembershipIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MembershipIdField, value) != true)) {
                    this.MembershipIdField = value;
                    this.RaisePropertyChanged("MembershipId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanNo {
            get {
                return this.PanNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PanNoField, value) != true)) {
                    this.PanNoField = value;
                    this.RaisePropertyChanged("PanNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinCode {
            get {
                return this.PinCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PinCodeField, value) != true)) {
                    this.PinCodeField = value;
                    this.RaisePropertyChanged("PinCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceTaxNo {
            get {
                return this.ServiceTaxNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceTaxNoField, value) != true)) {
                    this.ServiceTaxNoField = value;
                    this.RaisePropertyChanged("ServiceTaxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TanNo {
            get {
                return this.TanNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TanNoField, value) != true)) {
                    this.TanNoField = value;
                    this.RaisePropertyChanged("TanNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vat_TinNo {
            get {
                return this.Vat_TinNoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vat_TinNoField, value) != true)) {
                    this.Vat_TinNoField = value;
                    this.RaisePropertyChanged("Vat_TinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteUrl {
            get {
                return this.WebsiteUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteUrlField, value) != true)) {
                    this.WebsiteUrlField = value;
                    this.RaisePropertyChanged("WebsiteUrl");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResRegistration", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    public partial class ResRegistration : LetzGST.letzGST_Service.ResCommon {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqLogin", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CRequest")]
    [System.SerializableAttribute()]
    public partial class ReqLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqUpdatePassword", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CRequest")]
    [System.SerializableAttribute()]
    public partial class ReqUpdatePassword : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqOtp", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CRequest")]
    [System.SerializableAttribute()]
    public partial class ReqOtp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileNoField, value) != true)) {
                    this.mobileNoField = value;
                    this.RaisePropertyChanged("mobileNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqOtpValidate", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CRequest")]
    [System.SerializableAttribute()]
    public partial class ReqOtpValidate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int otpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string otpNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int otpId {
            get {
                return this.otpIdField;
            }
            set {
                if ((this.otpIdField.Equals(value) != true)) {
                    this.otpIdField = value;
                    this.RaisePropertyChanged("otpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string otpNo {
            get {
                return this.otpNoField;
            }
            set {
                if ((object.ReferenceEquals(this.otpNoField, value) != true)) {
                    this.otpNoField = value;
                    this.RaisePropertyChanged("otpNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqProfile", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CRequest")]
    [System.SerializableAttribute()]
    public partial class ReqProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GstinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MembershipIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PanNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceTaxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TanNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vat_TinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CinNo {
            get {
                return this.CinNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CinNoField, value) != true)) {
                    this.CinNoField = value;
                    this.RaisePropertyChanged("CinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNoField, value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GstinNo {
            get {
                return this.GstinNoField;
            }
            set {
                if ((object.ReferenceEquals(this.GstinNoField, value) != true)) {
                    this.GstinNoField = value;
                    this.RaisePropertyChanged("GstinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogoUrl {
            get {
                return this.LogoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoUrlField, value) != true)) {
                    this.LogoUrlField = value;
                    this.RaisePropertyChanged("LogoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipId {
            get {
                return this.MembershipIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MembershipIdField, value) != true)) {
                    this.MembershipIdField = value;
                    this.RaisePropertyChanged("MembershipId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanNo {
            get {
                return this.PanNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PanNoField, value) != true)) {
                    this.PanNoField = value;
                    this.RaisePropertyChanged("PanNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinCode {
            get {
                return this.PinCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PinCodeField, value) != true)) {
                    this.PinCodeField = value;
                    this.RaisePropertyChanged("PinCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceTaxNo {
            get {
                return this.ServiceTaxNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceTaxNoField, value) != true)) {
                    this.ServiceTaxNoField = value;
                    this.RaisePropertyChanged("ServiceTaxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TanNo {
            get {
                return this.TanNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TanNoField, value) != true)) {
                    this.TanNoField = value;
                    this.RaisePropertyChanged("TanNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vat_TinNo {
            get {
                return this.Vat_TinNoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vat_TinNoField, value) != true)) {
                    this.Vat_TinNoField = value;
                    this.RaisePropertyChanged("Vat_TinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteUrl {
            get {
                return this.WebsiteUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteUrlField, value) != true)) {
                    this.WebsiteUrlField = value;
                    this.RaisePropertyChanged("WebsiteUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqUserId", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CRequest")]
    [System.SerializableAttribute()]
    public partial class ReqUserId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqListUserCACompany", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CRequest")]
    [System.SerializableAttribute()]
    public partial class ReqListUserCACompany : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResUserListCACompany", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    public partial class ResUserListCACompany : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LetzGST.letzGST_Service.ResUserCACompany[] resUserCACompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LetzGST.letzGST_Service.ResUserCACompany[] resUserCACompany {
            get {
                return this.resUserCACompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.resUserCACompanyField, value) != true)) {
                    this.resUserCACompanyField = value;
                    this.RaisePropertyChanged("resUserCACompany");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResUserCACompany", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    public partial class ResUserCACompany : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNoField, value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResCompanyListCA", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    public partial class ResCompanyListCA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LetzGST.letzGST_Service.ResCompany_CA[] resCompany_CAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LetzGST.letzGST_Service.ResCompany_CA[] resCompany_CA {
            get {
                return this.resCompany_CAField;
            }
            set {
                if ((object.ReferenceEquals(this.resCompany_CAField, value) != true)) {
                    this.resCompany_CAField = value;
                    this.RaisePropertyChanged("resCompany_CA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResCompany_CA", Namespace="http://schemas.datacontract.org/2004/07/SoftonautsService.CResponse")]
    [System.SerializableAttribute()]
    public partial class ResCompany_CA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="letzGST_Service.ISNService")]
    public interface ISNService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/Registration", ReplyAction="http://tempuri.org/ISNService/RegistrationResponse")]
        LetzGST.letzGST_Service.ResRegistration Registration(LetzGST.letzGST_Service.ReqRegistration reqRegistration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/Registration", ReplyAction="http://tempuri.org/ISNService/RegistrationResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResRegistration> RegistrationAsync(LetzGST.letzGST_Service.ReqRegistration reqRegistration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/Login", ReplyAction="http://tempuri.org/ISNService/LoginResponse")]
        LetzGST.letzGST_Service.ResLogin Login(LetzGST.letzGST_Service.ReqLogin reqLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/Login", ReplyAction="http://tempuri.org/ISNService/LoginResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResLogin> LoginAsync(LetzGST.letzGST_Service.ReqLogin reqLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/UpdatePassword", ReplyAction="http://tempuri.org/ISNService/UpdatePasswordResponse")]
        LetzGST.letzGST_Service.ResCommon UpdatePassword(LetzGST.letzGST_Service.ReqUpdatePassword reqUpdatePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/UpdatePassword", ReplyAction="http://tempuri.org/ISNService/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCommon> UpdatePasswordAsync(LetzGST.letzGST_Service.ReqUpdatePassword reqUpdatePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/SendOtp", ReplyAction="http://tempuri.org/ISNService/SendOtpResponse")]
        LetzGST.letzGST_Service.ResOtp SendOtp(LetzGST.letzGST_Service.ReqOtp reqOtp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/SendOtp", ReplyAction="http://tempuri.org/ISNService/SendOtpResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResOtp> SendOtpAsync(LetzGST.letzGST_Service.ReqOtp reqOtp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/ValidateOtp", ReplyAction="http://tempuri.org/ISNService/ValidateOtpResponse")]
        LetzGST.letzGST_Service.ResCommon ValidateOtp(LetzGST.letzGST_Service.ReqOtpValidate reqValidateOtp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/ValidateOtp", ReplyAction="http://tempuri.org/ISNService/ValidateOtpResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCommon> ValidateOtpAsync(LetzGST.letzGST_Service.ReqOtpValidate reqValidateOtp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/InsertProfile", ReplyAction="http://tempuri.org/ISNService/InsertProfileResponse")]
        LetzGST.letzGST_Service.ResCommon InsertProfile(LetzGST.letzGST_Service.ReqProfile reqProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/InsertProfile", ReplyAction="http://tempuri.org/ISNService/InsertProfileResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCommon> InsertProfileAsync(LetzGST.letzGST_Service.ReqProfile reqProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/UpdateProfile", ReplyAction="http://tempuri.org/ISNService/UpdateProfileResponse")]
        LetzGST.letzGST_Service.ResCommon UpdateProfile(LetzGST.letzGST_Service.ReqProfile reqProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/UpdateProfile", ReplyAction="http://tempuri.org/ISNService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCommon> UpdateProfileAsync(LetzGST.letzGST_Service.ReqProfile reqProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/GetProfile", ReplyAction="http://tempuri.org/ISNService/GetProfileResponse")]
        LetzGST.letzGST_Service.ResProfile GetProfile(LetzGST.letzGST_Service.ReqUserId reqUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/GetProfile", ReplyAction="http://tempuri.org/ISNService/GetProfileResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResProfile> GetProfileAsync(LetzGST.letzGST_Service.ReqUserId reqUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/GetListUserCACompany", ReplyAction="http://tempuri.org/ISNService/GetListUserCACompanyResponse")]
        LetzGST.letzGST_Service.ResUserListCACompany GetListUserCACompany(LetzGST.letzGST_Service.ReqListUserCACompany reqListUserCACompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/GetListUserCACompany", ReplyAction="http://tempuri.org/ISNService/GetListUserCACompanyResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResUserListCACompany> GetListUserCACompanyAsync(LetzGST.letzGST_Service.ReqListUserCACompany reqListUserCACompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/GetListCACompany", ReplyAction="http://tempuri.org/ISNService/GetListCACompanyResponse")]
        LetzGST.letzGST_Service.ResCompanyListCA GetListCACompany(LetzGST.letzGST_Service.ReqUserId reqParentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNService/GetListCACompany", ReplyAction="http://tempuri.org/ISNService/GetListCACompanyResponse")]
        System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCompanyListCA> GetListCACompanyAsync(LetzGST.letzGST_Service.ReqUserId reqParentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISNServiceChannel : LetzGST.letzGST_Service.ISNService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SNServiceClient : System.ServiceModel.ClientBase<LetzGST.letzGST_Service.ISNService>, LetzGST.letzGST_Service.ISNService {
        
        public SNServiceClient() {
        }
        
        public SNServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SNServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SNServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SNServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LetzGST.letzGST_Service.ResRegistration Registration(LetzGST.letzGST_Service.ReqRegistration reqRegistration) {
            return base.Channel.Registration(reqRegistration);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResRegistration> RegistrationAsync(LetzGST.letzGST_Service.ReqRegistration reqRegistration) {
            return base.Channel.RegistrationAsync(reqRegistration);
        }
        
        public LetzGST.letzGST_Service.ResLogin Login(LetzGST.letzGST_Service.ReqLogin reqLogin) {
            return base.Channel.Login(reqLogin);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResLogin> LoginAsync(LetzGST.letzGST_Service.ReqLogin reqLogin) {
            return base.Channel.LoginAsync(reqLogin);
        }
        
        public LetzGST.letzGST_Service.ResCommon UpdatePassword(LetzGST.letzGST_Service.ReqUpdatePassword reqUpdatePassword) {
            return base.Channel.UpdatePassword(reqUpdatePassword);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCommon> UpdatePasswordAsync(LetzGST.letzGST_Service.ReqUpdatePassword reqUpdatePassword) {
            return base.Channel.UpdatePasswordAsync(reqUpdatePassword);
        }
        
        public LetzGST.letzGST_Service.ResOtp SendOtp(LetzGST.letzGST_Service.ReqOtp reqOtp) {
            return base.Channel.SendOtp(reqOtp);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResOtp> SendOtpAsync(LetzGST.letzGST_Service.ReqOtp reqOtp) {
            return base.Channel.SendOtpAsync(reqOtp);
        }
        
        public LetzGST.letzGST_Service.ResCommon ValidateOtp(LetzGST.letzGST_Service.ReqOtpValidate reqValidateOtp) {
            return base.Channel.ValidateOtp(reqValidateOtp);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCommon> ValidateOtpAsync(LetzGST.letzGST_Service.ReqOtpValidate reqValidateOtp) {
            return base.Channel.ValidateOtpAsync(reqValidateOtp);
        }
        
        public LetzGST.letzGST_Service.ResCommon InsertProfile(LetzGST.letzGST_Service.ReqProfile reqProfile) {
            return base.Channel.InsertProfile(reqProfile);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCommon> InsertProfileAsync(LetzGST.letzGST_Service.ReqProfile reqProfile) {
            return base.Channel.InsertProfileAsync(reqProfile);
        }
        
        public LetzGST.letzGST_Service.ResCommon UpdateProfile(LetzGST.letzGST_Service.ReqProfile reqProfile) {
            return base.Channel.UpdateProfile(reqProfile);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCommon> UpdateProfileAsync(LetzGST.letzGST_Service.ReqProfile reqProfile) {
            return base.Channel.UpdateProfileAsync(reqProfile);
        }
        
        public LetzGST.letzGST_Service.ResProfile GetProfile(LetzGST.letzGST_Service.ReqUserId reqUserId) {
            return base.Channel.GetProfile(reqUserId);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResProfile> GetProfileAsync(LetzGST.letzGST_Service.ReqUserId reqUserId) {
            return base.Channel.GetProfileAsync(reqUserId);
        }
        
        public LetzGST.letzGST_Service.ResUserListCACompany GetListUserCACompany(LetzGST.letzGST_Service.ReqListUserCACompany reqListUserCACompany) {
            return base.Channel.GetListUserCACompany(reqListUserCACompany);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResUserListCACompany> GetListUserCACompanyAsync(LetzGST.letzGST_Service.ReqListUserCACompany reqListUserCACompany) {
            return base.Channel.GetListUserCACompanyAsync(reqListUserCACompany);
        }
        
        public LetzGST.letzGST_Service.ResCompanyListCA GetListCACompany(LetzGST.letzGST_Service.ReqUserId reqParentId) {
            return base.Channel.GetListCACompany(reqParentId);
        }
        
        public System.Threading.Tasks.Task<LetzGST.letzGST_Service.ResCompanyListCA> GetListCACompanyAsync(LetzGST.letzGST_Service.ReqUserId reqParentId) {
            return base.Channel.GetListCACompanyAsync(reqParentId);
        }
    }
}
